# 端口服务
server:
  port: 8090
  address: localhost
  servlet:
    context-path: /

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/rabbitmq
    dbname: rabbitmq
    parameters: ?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver